### ISSUE TITLE
С кем вы собираетесь сравнивать сервис?

### ISSUE THREAD

**Issue by coursar** [stanislavryzhikov/Realty#3]
https://github.com/stanislavryzhikov/Realty/blob/a0cc92f0a2f32ff5a9cab442f4316fe1c16ae9e4/src/ru/itpark/service/RealtyService.java#L32-L38

В большинстве случаем .equals имеет смысл для классов, содержащих данные (не для сервисов).

**Comment by stanislavryzhikov** [comment]
Исправил

**Comment by stanislavryzhikov** [comment]
done
