### ISSUE TITLE
Если это массив, то должен называться names, а не name

### ISSUE THREAD

**Issue by coursar** [stanislavryzhikov/Realty#4]
https://github.com/stanislavryzhikov/Realty/blob/a0cc92f0a2f32ff5a9cab442f4316fe1c16ae9e4/src/ru/itpark/service/RealtyService.java#L45

**Comment by stanislavryzhikov** [comment]
Исправил

**Comment by coursar** [comment]
Закрывайте баги через сообщения комитта.
