### ISSUE TITLE
Что если убрать префикс realty? Поля же итак находятся в классе Realty.

### ISSUE THREAD

**Issue by coursar** [stanislavryzhikov/Realty#7]
https://github.com/stanislavryzhikov/Realty/blob/a0cc92f0a2f32ff5a9cab442f4316fe1c16ae9e4/src/ru/itpark/domain/Realty.java#L4-L5

**Comment by stanislavryzhikov** [comment]
думаю, что лучше исправить

**Comment by stanislavryzhikov** [comment]
done
